apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chocoletter-chat-sonhs-com
  namespace: gateway # Gateway 네임스페이스
spec:
  secretName: chocoletter-chat-sonhs-com-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - chocoletter-chat.sonhs.com
