apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chocoletter-external-secret-chat
  namespace: chocoletter
spec:
  refreshInterval: 1h # 시크릿 갱신 주기
  secretStoreRef:
    name: aws-secrets-mgr
    kind: SecretStore
  target:
    name: chocoletter-chat-secret # 생성될 로컬 K8s Secret 이름
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "prod/chocoletter-chat"