apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: chocoletter-chat-route
  namespace: chocoletter
spec:
  parentRefs:
    - name: web-gateway
      namespace: gateway # Gateway가 있는 ns
      sectionName: http-chocoletter-chat
#    - name: web-gateway
#      namespace: gateway # Gateway가 있는 ns
#      sectionName: https-chocoletter-chat
  hostnames:
    - chocoletter-chat.sonhs.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: chocoletter-chat-service
          port: 80
