apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: chocoletter-server-after-route
  namespace: chocoletter
spec:
  parentRefs:
    - name: web-gateway
      namespace: gateway # Gateway가 있는 ns
      sectionName: http-chocoletter-server-after
    - name: web-gateway
      namespace: gateway # Gateway가 있는 ns
      sectionName: https-chocoletter-server-after
  hostnames:
    - chocoletter-server-after.sonhs.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: chocoletter-server-after-service
          port: 80