apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocoletter-client-after-deploy
  namespace: chocoletter
  labels:
    app: chocoletter-client-after
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chocoletter-client-after
  template:
    metadata:
      labels:
        app: chocoletter-client-after
    spec:
      imagePullSecrets:
        - name: ecr-registry-key
      containers:
        - name: chocoletter-client-after
          image: 211125633965.dkr.ecr.ap-northeast-2.amazonaws.com/refac/chocoletter-client-after:1.1
          ports:
            - containerPort: 80
