apiVersion: v1
kind: Service
metadata:
  name: chocoletter-client-after-service
  namespace: chocoletter
spec:
  selector:
    app: chocoletter-client-after
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80