apiVersion: v1
kind: Service
metadata:
  name: chocoletter-server-service
  namespace: chocoletter
spec:
  type: ClusterIP
  selector:
    app: chocoletter-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080